# Overwrite bitnami postgresql values
#
postgresql:
  image:
    tag: "10.22.0-debian-11-r6"
  # tag: "14.4.0-debian-11-r19"

  containerPorts:
    postgresql: 5432

  networkPolicy:
    create: false

