---
postgresql:
  global:
    storageClass: ""
  auth:
    ##
    username: "demo-user"
    database: "demo"
    existingSecret: "postgres-user"
  primary:
    persistence:
      size: 2Gi
    initdb:
      scripts:
        create_db.sql: |
          CREATE DATABASE datastore WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'C';
          ALTER DATABASE datastore OWNER TO "demo-user";

  backup:
    ## @param backup.enabled Enable the logical dump of the database "regularly"
    enabled: true
    cronjob:
      ## @param backup.cronjob.schedule Set the cronjob parameter schedule
      # schedule: "@hourly"
      schedule: "*/5 * * * *"
      ttlSecondsAfterFinished: "400"
    podSecurityContext:
      enabled: false
    containerSecurityContext: {}
    labels: {}
    storage:
      size: 2Gi
      resourcePolicy: "keep"
  metrics:
    ## @param metrics.enabled Start a prometheus exporter
    enabled: false
