---
postgresql:
  global:
    storageClass: ""
  auth:
    ##
    username: "myuser"
    existingSecret: "postgres-user"
  primary:
    initdb:
      scripts:
        create_db.sql: |
          CREATE DATABASE brxm WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'C';
          ALTER DATABASE brxm OWNER TO "dpc-oa";
          CREATE DATABASE datastore WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'C';
          ALTER DATABASE datastore OWNER TO "dpc-oa";

  backup:
    ## @param backup.enabled Enable the logical dump of the database "regularly"
    enabled: true
    cronjob:
      ## @param backup.cronjob.schedule Set the cronjob parameter schedule
      # schedule: "@hourly"
      schedule: "*/5 * * * *"
      ttlSecondsAfterFinished: "400"
    podSecurityContext:
      enabled: false
    containerSecurityContext: {}
    labels: {}
    storage:
      size: 2Gi
      resourcePolicy: "keep"
  metrics:
    ## @param metrics.enabled Start a prometheus exporter
    enabled: false
