apiVersion: v2
name: postgresql
description: Umbrella chart for bitnami postgresql

type: application

version: 1.0.0
appVersion: "15.6.0"

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.5.1
