---
{{- if .Values.postgresql.sealedSecrets.enabled }}
{{- $releaseName := .Release.Name -}}
{{- range .Values.postgresql.sealedSecrets.secrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  {{- with .annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $releaseName }}-{{ .secretName }}
spec:
  encryptedData: {{ toYaml .encryptedData | nindent 6 }}
  template:
    metadata:
      {{- with .annotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .app }}
      name: {{ $releaseName }}-{{ .secretName }}
    type: Opaque
{{- end }}
{{- end }}
